-- ─── Seed Data: 20 Nigerian Hospitals Across 5 Cities ───────────────────────
-- Cities: Lagos, Abuja, Kano, Port Harcourt, Ibadan

INSERT INTO public.hospitals (
  name, address, city, lga, phone, email,
  specialties, ownership, location, latitude, longitude,
  description_md, visiting_hours
) VALUES

-- ─── Lagos (4 hospitals) ──────────────────────────────────────────────────────
(
  'Lagos University Teaching Hospital',
  'Idiaraba, Lagos Island',
  'Lagos',
  'Lagos Island',
  '+2341234567890',
  'info@luth.gov.ng',
  ARRAY['emergency', 'maternity', 'pediatric', 'cardiology', 'neurology'],
  'public',
  ST_MakePoint(3.3792, 6.5244)::GEOGRAPHY,
  6.5244, 3.3792,
  '## Lagos University Teaching Hospital\n\nLUTH is one of Nigeria''s premier teaching hospitals, providing world-class healthcare to Lagos residents and beyond. Established in 1962, it serves as a training ground for medical professionals and a referral centre for complex cases.\n\n### Facilities\n- 24/7 Emergency Department\n- Neonatal Intensive Care Unit\n- Cardiac Catheterisation Laboratory\n- Modern Radiology Suite',
  'General: Monday–Friday 10:00–12:00 and 16:00–18:00\nICU: Restricted visiting, contact ward directly'
),
(
  'Reddington Hospital',
  'Victoria Island, Lagos',
  'Lagos',
  'Eti-Osa',
  '+2348012345678',
  'contact@reddingtonhospital.com',
  ARRAY['emergency', 'cardiology', 'orthopedic', 'general'],
  'private',
  ST_MakePoint(3.4347, 6.4281)::GEOGRAPHY,
  6.4281, 3.4347,
  '## Reddington Hospital\n\nA leading private hospital on Victoria Island offering premium healthcare services with state-of-the-art equipment and internationally trained specialists.\n\n### Services\n- Executive Health Screening\n- Cardiology Centre\n- Orthopaedic & Trauma Unit\n- 24-hour Pharmacy',
  'Monday–Sunday: Open 24 hours\nVisiting Hours: 10:00–20:00'
),
(
  'Island General Hospital',
  'Catholic Mission Street, Lagos Island',
  'Lagos',
  'Lagos Island',
  '+2341234500001',
  'islandgeneral@lagosstate.gov.ng',
  ARRAY['emergency', 'maternity', 'general', 'pediatric'],
  'public',
  ST_MakePoint(3.3958, 6.4541)::GEOGRAPHY,
  6.4541, 3.3958,
  '## Island General Hospital\n\nA government-owned general hospital serving the Lagos Island community with affordable and accessible healthcare services.\n\n### Key Services\n- Antenatal and Postnatal Care\n- Children''s Ward\n- Accident & Emergency\n- Outpatient Clinics',
  'Outpatient: Monday–Friday 08:00–16:00\nEmergency: 24 hours daily'
),
(
  'Eko Hospital',
  'Plot 31, Mobolaji Bank Anthony Way, Ikeja',
  'Lagos',
  'Ikeja',
  '+2348023456789',
  'info@ekohospitals.com',
  ARRAY['cardiology', 'neurology', 'oncology', 'maternity', 'emergency'],
  'private',
  ST_MakePoint(3.3464, 6.6018)::GEOGRAPHY,
  6.6018, 3.3464,
  '## Eko Hospital\n\nEko Hospital is one of Nigeria''s most advanced private hospitals, offering comprehensive specialist care across multiple disciplines.\n\n### Specialties\n- Cardiac Surgery Unit\n- Neuroscience Centre\n- Cancer Treatment Centre\n- Women''s Health & Maternity',
  'Visiting Hours: Daily 12:00–14:00 and 17:00–19:00\nEmergency: 24 hours'
),

-- ─── Abuja (4 hospitals) ──────────────────────────────────────────────────────
(
  'National Hospital Abuja',
  'Central Business District, Abuja',
  'Abuja',
  'Municipal Area Council',
  '+2349012345678',
  'info@nationalhospital.gov.ng',
  ARRAY['emergency', 'cardiology', 'neurology', 'oncology', 'maternity'],
  'public',
  ST_MakePoint(7.4898, 9.0579)::GEOGRAPHY,
  9.0579, 7.4898,
  '## National Hospital Abuja\n\nThe National Hospital Abuja is a federal government tertiary health institution providing specialised medical care to residents of the FCT and surrounding states.\n\n### Facilities\n- National Cardiovascular Centre\n- Renal Dialysis Unit\n- Neurosurgery Department\n- Radiotherapy & Oncology Centre',
  'Outpatient: Monday–Friday 08:00–15:00\nEmergency: 24 hours daily'
),
(
  'Garki Hospital',
  'Garki Area 1, Abuja',
  'Abuja',
  'Municipal Area Council',
  '+2349023456789',
  'garkihospital@fct.gov.ng',
  ARRAY['general', 'maternity', 'pediatric', 'dental'],
  'public',
  ST_MakePoint(7.4803, 9.0417)::GEOGRAPHY,
  9.0417, 7.4803,
  '## Garki Hospital\n\nGarki Hospital is a secondary healthcare facility under the FCT Health Secretariat, providing accessible care to residents of Abuja.\n\n### Services\n- Family Medicine Clinic\n- Dental Unit\n- Children''s Health Services\n- Maternity Ward',
  'Monday–Friday: 08:00–17:00\nSaturday: 09:00–14:00\nEmergency: 24 hours'
),
(
  'Cedarcrest Hospitals',
  'Plot 1837, Cadastral Zone A00, Central Business District, Abuja',
  'Abuja',
  'Municipal Area Council',
  '+2348034567890',
  'info@cedarcresthospitals.com',
  ARRAY['cardiology', 'orthopedic', 'maternity', 'emergency', 'general'],
  'private',
  ST_MakePoint(7.4951, 9.0697)::GEOGRAPHY,
  9.0697, 7.4951,
  '## Cedarcrest Hospitals\n\nCedarcrest is a leading private hospital group in Abuja offering tertiary-level care with modern facilities and experienced specialists.\n\n### Highlights\n- Joint Replacement Centre\n- Maternal & Fetal Medicine Unit\n- Cardiac Rehabilitation\n- 24-hour Emergency',
  'Open 24 hours, 7 days a week\nVisiting: 11:00–13:00 and 17:00–19:00'
),
(
  'Maitama District Hospital',
  'Maitama District, Abuja',
  'Abuja',
  'Municipal Area Council',
  '+2349034567891',
  'maitama@fct.gov.ng',
  ARRAY['general', 'emergency', 'pediatric', 'maternity'],
  'public',
  ST_MakePoint(7.5003, 9.0833)::GEOGRAPHY,
  9.0833, 7.5003,
  '## Maitama District Hospital\n\nA government district hospital serving the upscale Maitama community with primary and secondary healthcare services.\n\n### Services\n- General Outpatient Department\n- Children''s Clinic\n- Antenatal Care\n- Accident & Emergency',
  'Monday–Saturday: 08:00–16:00\nEmergency: 24 hours'
),

-- ─── Kano (4 hospitals) ───────────────────────────────────────────────────────
(
  'Aminu Kano Teaching Hospital',
  'Zoo Road, Kano',
  'Kano',
  'Nasarawa',
  '+2348045678901',
  'info@akth.gov.ng',
  ARRAY['emergency', 'cardiology', 'neurology', 'maternity', 'pediatric', 'oncology'],
  'public',
  ST_MakePoint(8.5165, 12.0022)::GEOGRAPHY,
  12.0022, 8.5165,
  '## Aminu Kano Teaching Hospital\n\nAKTH is one of northern Nigeria''s most important tertiary hospitals, providing specialist care and medical education across a wide range of disciplines.\n\n### Departments\n- Paediatrics & Child Health\n- Obstetrics & Gynaecology\n- Internal Medicine\n- Surgery & Trauma',
  'Outpatient: Monday–Friday 08:00–14:00\nEmergency: 24 hours'
),
(
  'Murtala Mohammed Specialist Hospital',
  'Hospital Road, Kano',
  'Kano',
  'Kano Municipal',
  '+2348056789012',
  'mmsh@kanostate.gov.ng',
  ARRAY['general', 'maternity', 'emergency', 'dental', 'ophthalmology'],
  'public',
  ST_MakePoint(8.5277, 11.9985)::GEOGRAPHY,
  11.9985, 8.5277,
  '## Murtala Mohammed Specialist Hospital\n\nA Kano State specialist hospital providing secondary and tertiary care to residents across Kano and neighbouring states.\n\n### Services\n- Eye Centre (Ophthalmology)\n- Dental Clinic\n- Women''s Health Unit\n- Emergency Services',
  'Monday–Friday: 08:00–16:00\nEmergency: 24 hours daily'
),
(
  'Hasiya Bayero Paediatric Hospital',
  'Tarauni, Kano',
  'Kano',
  'Tarauni',
  '+2348067890123',
  'hbph@kanostate.gov.ng',
  ARRAY['pediatric', 'maternity', 'emergency'],
  'public',
  ST_MakePoint(8.5432, 12.0156)::GEOGRAPHY,
  12.0156, 8.5432,
  '## Hasiya Bayero Paediatric Hospital\n\nA dedicated paediatric hospital providing specialised child healthcare across Kano State.\n\n### Services\n- Neonatal Care\n- Child Surgery\n- Paediatric Emergency\n- Vaccination & Immunisation',
  'Monday–Friday: 08:00–16:00\nEmergency: 24 hours'
),
(
  'Kano Specialist Clinic',
  'Fagge LGA, Kano',
  'Kano',
  'Fagge',
  '+2348078901234',
  'info@kanospecialist.com',
  ARRAY['general', 'dental', 'ophthalmology', 'orthopedic'],
  'private',
  ST_MakePoint(8.5100, 11.9950)::GEOGRAPHY,
  11.9950, 8.5100,
  '## Kano Specialist Clinic\n\nA private specialist clinic in Kano offering quality outpatient and diagnostic services.\n\n### Services\n- Eye Care & Glasses Fitting\n- Dental & Orthodontic Care\n- Orthopaedic Consultations\n- Laboratory & Diagnostics',
  'Monday–Saturday: 08:00–18:00'
),

-- ─── Port Harcourt (4 hospitals) ─────────────────────────────────────────────
(
  'University of Port Harcourt Teaching Hospital',
  'East-West Road, Choba, Port Harcourt',
  'Port Harcourt',
  'Obio-Akpor',
  '+2348089012345',
  'info@upth.gov.ng',
  ARRAY['emergency', 'cardiology', 'neurology', 'maternity', 'oncology', 'pediatric'],
  'public',
  ST_MakePoint(7.0134, 4.8396)::GEOGRAPHY,
  4.8396, 7.0134,
  '## University of Port Harcourt Teaching Hospital\n\nUPTH is the premier teaching hospital in Rivers State, providing tertiary healthcare and training future medical professionals.\n\n### Key Departments\n- Cardiothoracic Surgery\n- Oncology & Radiotherapy\n- Maternal & Fetal Medicine\n- Neurosurgery',
  'Outpatient: Monday–Friday 08:00–15:00\nEmergency: 24 hours'
),
(
  'Braithwaite Memorial Specialist Hospital',
  'Moscow Road, Port Harcourt',
  'Port Harcourt',
  'Port Harcourt City',
  '+2348090123456',
  'bmsh@riversstate.gov.ng',
  ARRAY['general', 'maternity', 'emergency', 'pediatric', 'dental'],
  'public',
  ST_MakePoint(7.0134, 4.7754)::GEOGRAPHY,
  4.7754, 7.0134,
  '## Braithwaite Memorial Specialist Hospital\n\nOne of the oldest and most respected government hospitals in Rivers State, serving Port Harcourt residents since 1925.\n\n### Services\n- Specialist Clinics\n- Obstetrics & Gynaecology\n- Paediatric Ward\n- Laboratory & Blood Bank',
  'Monday–Friday: 08:00–16:00\nEmergency: 24 hours'
),
(
  'Meridian Hospital Port Harcourt',
  'GRA Phase 2, Port Harcourt',
  'Port Harcourt',
  'Obio-Akpor',
  '+2348101234567',
  'info@meridianhospitalph.com',
  ARRAY['cardiology', 'orthopedic', 'maternity', 'emergency', 'general'],
  'private',
  ST_MakePoint(7.0201, 4.8105)::GEOGRAPHY,
  4.8105, 7.0201,
  '## Meridian Hospital\n\nA premium private hospital in GRA Port Harcourt providing specialist care with modern equipment.\n\n### Services\n- Cardiac & Vascular Surgery\n- Joint Replacement\n- IVF & Fertility Centre\n- 24-hour Emergency',
  'Open 24 hours\nVisiting: 12:00–14:00 and 17:00–19:00'
),
(
  'Rivers State University Teaching Hospital',
  'Diobu, Port Harcourt',
  'Port Harcourt',
  'Port Harcourt City',
  '+2348112345678',
  'rsuth@riversstate.gov.ng',
  ARRAY['emergency', 'general', 'maternity', 'pediatric', 'neurology'],
  'public',
  ST_MakePoint(6.9980, 4.7800)::GEOGRAPHY,
  4.7800, 6.9980,
  '## Rivers State University Teaching Hospital\n\nRSUTH provides tertiary healthcare and medical education across Rivers State.\n\n### Departments\n- Internal Medicine\n- Surgery\n- Obstetrics & Gynaecology\n- Accident & Emergency',
  'Outpatient: Monday–Friday 08:00–15:00\nEmergency: 24 hours'
),

-- ─── Ibadan (4 hospitals) ─────────────────────────────────────────────────────
(
  'University College Hospital Ibadan',
  'Queen Elizabeth Road, Ibadan',
  'Ibadan',
  'Ibadan North',
  '+2348123456789',
  'info@uch.edu.ng',
  ARRAY['emergency', 'cardiology', 'neurology', 'oncology', 'maternity', 'pediatric', 'orthopedic'],
  'public',
  ST_MakePoint(3.8966, 7.4009)::GEOGRAPHY,
  7.4009, 3.8966,
  '## University College Hospital Ibadan\n\nUCH Ibadan is Nigeria''s first and most prestigious teaching hospital, established in 1952. It remains one of Africa''s leading centres for medical care and research.\n\n### World-Class Facilities\n- Cancer Treatment Centre\n- Cardiac Surgery Unit\n- Neuroscience Institute\n- Bone Marrow Transplant Unit\n- Neonatal Intensive Care',
  'Outpatient: Monday–Friday 08:00–15:00\nEmergency: 24 hours\nICU: Restricted — contact ward'
),
(
  'Adeoyo Maternity Hospital',
  'Ring Road, Ibadan',
  'Ibadan',
  'Ibadan North',
  '+2348134567890',
  'adeoyo@oyostate.gov.ng',
  ARRAY['maternity', 'pediatric', 'emergency'],
  'public',
  ST_MakePoint(3.9012, 7.3895)::GEOGRAPHY,
  7.3895, 3.9012,
  '## Adeoyo Maternity Hospital\n\nAdeoyo is Oyo State''s dedicated maternity hospital, providing comprehensive maternal and child health services to Ibadan residents.\n\n### Services\n- Antenatal & Postnatal Care\n- Safe Delivery Services\n- Neonatal Care Unit\n- Family Planning Clinic',
  'Monday–Saturday: 08:00–17:00\nEmergency Maternity: 24 hours'
),
(
  'Jericho Nursing Home',
  'Jericho GRA, Ibadan',
  'Ibadan',
  'Ibadan North',
  '+2348145678901',
  'info@jerichonursinghome.com',
  ARRAY['maternity', 'general', 'pediatric', 'dental'],
  'private',
  ST_MakePoint(3.9100, 7.4100)::GEOGRAPHY,
  7.4100, 3.9100,
  '## Jericho Nursing Home\n\nA well-established private hospital in the heart of Jericho GRA, providing quality healthcare in a comfortable environment.\n\n### Services\n- Maternity & Baby Care\n- Paediatric Outpatient\n- Dental Clinic\n- General Practice',
  'Monday–Saturday: 08:00–20:00\nEmergency: 24 hours'
),
(
  'Oluyoro Catholic Hospital',
  'Oke Offa, Ibadan',
  'Ibadan',
  'Ibadan North-East',
  '+2348156789012',
  'info@oluyoro.org',
  ARRAY['general', 'maternity', 'pediatric', 'emergency', 'ophthalmology'],
  'private',
  ST_MakePoint(3.9205, 7.4200)::GEOGRAPHY,
  7.4200, 3.9205,
  '## Oluyoro Catholic Hospital\n\nA mission hospital run by the Catholic Diocese of Ibadan, providing compassionate and affordable care to all regardless of faith.\n\n### Services\n- Eye Care Centre\n- Women & Children Health\n- General Surgery\n- Community Outreach Programs',
  'Monday–Friday: 08:00–17:00\nSaturday: 08:00–14:00\nEmergency: 24 hours'
);